HIESPath: D:/MajidFiles/HEIS/
HIESRARPath: D:/MajidFiles/HEIS/RARs/
HIESRAWPath: D:/MajidFiles/HEIS/DataRAW/
HIESSummaryPath: D:/MajidFiles/HEIS/Summary/
startyear: 63.0
endyear: 92.0
OS: windows
RawDataWebAddress: http://www.amar.org.ir/Portals/0/amarmozuii/hazinedaramad/

