HIESPath: D:/MajidFiles/HEIS/
HIESRARPath: D:/MajidFiles/HEIS/RARs/
HIESRAWPath: D:/MajidFiles/HEIS/RAW/
HIESSummaryPath: D:/MajidFiles/HEIS/Summary/
startyear: 70.0
endyear: 92.0
os: windows
RawDataWebAddress: http://www.amar.org.ir/Portals/0/amarmozuii/hazinedaramad/

